name: Github Actions Demo
on: push
jobs:
  Example-Actions-Jobs:
    name: Exploring Github Actions
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name}} event"
      
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
  
  Second-Job:
    name: The second job runs on another runner
    runs-on: ubuntu-latest
    needs: Example-Actions-Jobs
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name}} event on the second runner" 